plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.js
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-berry.js

packageExtensions:
  "eslint-config-standard-with-typescript@*":
    peerDependencies:
      eslint: "*"
      eslint-plugin-import: "*"
      typescript: "*"